name: Build from tarball

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**.nix'
      - eslint.config.mjs
      - '**/eslint.config_partial.mjs'
      - android-configure
      - android-configure.py
      - android-patches/**
      - benchmarks/**
      - codecov.yml
      - doc/**
      - pyproject.yml
      - tsconfig.json
      - test/internet/**
      - tools/actions/**
      - tools/dep_updaters/**
      - tools/doc/**
      - tools/eslint-rules/**
      - tools/eslint/**
      - tools/lint-md/**
      - tools/nix/**
      - typings/**
      - vcbuild.bat
      - .**
      - '!.github/workflows/build-tarball.yml'
  push:
    branches:
      - main
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - '**.md'
      - '**.nix'
      - eslint.config.mjs
      - '**/eslint.config_partial.mjs'
      - android-configure
      - android-configure.py
      - android-patches/**
      - benchmarks/**
      - codecov.yml
      - doc/**
      - pyproject.yml
      - tsconfig.json
      - test/internet/**
      - tools/actions/**
      - tools/dep_updaters/**
      - tools/doc/**
      - tools/eslint-rules/**
      - tools/eslint/**
      - tools/lint-md/**
      - tools/nix/**
      - typings/**
      - vcbuild.bat
      - .**
      - '!.github/workflows/build-tarball.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.14'
  FLAKY_TESTS: keep_retrying
  CLANG_VERSION: '19'
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  build-tarball:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-slim
    strategy:
      matrix:
        GZ_COMPRESSION: [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
        ]
        n: [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
        ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          allow-prereleases: true
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Make tarball
        run: |
          export DISTTYPE=nightly
          export DATESTRING=$(date "+%Y-%m-%d")
          export COMMIT=$(git rev-parse --short=10 "$GITHUB_SHA")
          ./configure && make tar -j4 SKIP_XZ=1 SKIP_SHARED_DEPS=1 GZ_COMPRESSION=${{ matrix.GZ_COMPRESSION }}
      - name: Upload tarball artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          path: '*.tar.gz'
          archive: false
