name: Linters (release proposals)

on:
  push:
    branches:
      - v[0-9]+.[0-9]+.[0-9]+-proposal

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.12'
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  lint-release-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Lint release commit title format
        run: |
          git --no-pager log -1 --format=%s | grep -q -E '^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}, Version [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ (\(Current|'.+' \(LTS)\)$'
      - name: Lint release commit message trailers
        run: |
          EXPECTED_TRAILER="^PR-URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/[[:digit:]]+\$"
          echo "$EXPECTED_TRAILER"
          git --no-pager log -1 --format=%b | git interpret-trailers --parse --no-divider | grep -E -q "$EXPECTED_TRAILER"
      - name: Extract releaser info
        id: releaser-info
        run: |
          COMMIT_SUBJECT="$(git --no-pager log -1 --format=%s)"
          CHANGELOG_TITLE_INTRO="## $COMMIT_SUBJECT, @"
          CHANGELOG_TITLE="$(grep "$CHANGELOG_TITLE_INTRO" "doc/changelogs/CHANGELOG_V${COMMIT_SUBJECT:20:2}.md")"
          [[ "${CHANGELOG_TITLE%@*}@" == "$CHANGELOG_TITLE_INTRO" ]]
          RELEASER_INFO="${CHANGELOG_TITLE#*@}"
          {
            echo "RELEASER=${RELEASER_INFO% prepared by*}"
            echo "PREPARATOR=${RELEASER_INFO#*@}"
          } >> "$GITHUB_OUTPUT"
      - name: Verify NODE_VERSION_IS_RELEASE bit is correctly set
        run: |
          grep -q '^#define NODE_VERSION_IS_RELEASE 1$' src/node_version.h
