name: Tests

on:
  pull_request:

jobs:
  chore:
    name: "Testing chores"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: git --no-pager diff --name-only HEAD^
      - run: git --no-pager diff --name-only HEAD^2
